### PR TITLE
Fix missing parentheses in instance declaration of type operators.

### LINKED ISSUE #342: Breaks instances with type operators
``` haskell
instance Foo (->)
```

is reformatted as

``` haskell
instance Foo ->
```

on bab6839.

### PR DESCRIPTION
**Pull request by sighingnow**
Fix #342.

### CODE REVIEW

File: src/HIndent/Pretty.hs [hunk 1]
```diff
@@ -1554,7 +1554,16 @@ typ x = case x of
                 space
                 pretty a
           TyVar _ n -> pretty n
-          TyCon _ p -> pretty p
+          TyCon _ p -> case p of
```
Comment (wiz) [inline src/HIndent/Pretty.hs]: Does not follow module's code style, pls fix.

Comment (sighingnow) [inline src/HIndent/Pretty.hs]: OK, I have fixed it.
