### PR TITLE
fix type family annotation handling

### LINKED ISSUE #314: Type family declarations lead to unparsable code
In the following example

```haskell
~> hindent
{-# LANGUAGE TypeFamilies #-}

module Foo where

type family Foo a :: *
{-# LANGUAGE TypeFamilies #-}

module Foo where

type family Foo a = *
```

The `:: *` becomes `= *` which is invalid code.

This is running against bdee6d4138aca96bfd8f39f4e5d5e3fd3d17523d.

### PR DESCRIPTION
**Pull request by Bogdanp**
I believe this fixes #314

### CODE REVIEW

File: src/HIndent/Pretty.hs [hunk 1]
```diff
@@ -782,7 +782,10 @@ decl (TypeFamDecl _ declhead result injectivity) = do
   case result of
     Just r -> do
       space
-      write "="
+      let sep = case r of
+                  KindSig _ _ -> "::"
+                  TyVarSig _ _ -> "="
```
Comment (cblp) [inline src/HIndent/Pretty.hs]: KindSig{}, TyVarSig{}

**Comment by chrisdone** [comment]
Thanks!
